### ISSUE TITLE
Converting text with numbers and words

### ISSUE THREAD

**Issue by dataBaseError** [dimidd/numbers_in_words#1]
Moved from https://github.com/markburns/numbers_in_words. I tested the latest version and it still seems to have an issue with a combination of numbers and number words. E.g. 

```
'100 Million'.in_numbers
=> 1000000
```

Which should evaluate to `100000000`.

**Comment by dimidd** [comment]
Added. However, complex mixed strings such as "2 million 35 thousand 55" aren't supported yet.

**Comment by dataBaseError** [comment]
Fantastic, thank you very much.
